CREATE TABLE ARTIST (DATE_OF_BIRTH date NULL, ID serial NOT NULL, NAME varchar(200) NULL, PRIMARY KEY (ID));

CREATE TABLE GALLERY (ID serial NOT NULL, NAME varchar(200) NULL, PRIMARY KEY (ID));

CREATE TABLE PAINTING (ARTIST_ID integer NULL, GALLERY_ID integer NULL, ID serial NOT NULL, NAME varchar(200) NULL, PRIMARY KEY (ID));

ALTER TABLE PAINTING ADD FOREIGN KEY (ARTIST_ID) REFERENCES ARTIST (ID);

ALTER TABLE PAINTING ADD FOREIGN KEY (GALLERY_ID) REFERENCES GALLERY (ID);

